rotors:
- "NVTDFMXHQPWIESJZLCAUKRGYBO"
- "RNKXALDZIOBHTWYJEVCQMPFGSU"
- "HXOIRGSBVLTEQPAMDKWFCZNUJY"
reflector: "VSFJHCWEYDNXQKUZMTBROAGLIP"
plugs:
- "BT"
- "IS"
- "PC"
- "YH"
- "ZR"
- "GD"
- "XN"
- "UW"
- "LO"
- "MJ"
- "QE"
- "AF"
- "KV"
positions:
- 1
- 15
- 9
alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
